/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;

import Doctor.Doctor;
import Payments.Payments;
import Pharmacy.Login.Login;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zubery Ayyub, Nobert Okoye, Ahmed Meshref
 */
public class Pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form Pharmacy
     */
    public Pharmacy() {
        initComponents();
        ImageIcon img;
        img = new ImageIcon("C:\\Users\\Zoubar\\Documents\\NetBeansProjects\\Pharmacy_Project\\src\\Icons/icon1.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jxtReferenceNo = new javax.swing.JTextField();
        Name_of_Tablet = new javax.swing.JLabel();
        jxtDose = new javax.swing.JTextField();
        jxtNumberofTablets = new javax.swing.JTextField();
        Dose_mg = new javax.swing.JLabel();
        jxtReferenceNo6 = new javax.swing.JTextField();
        Number_of_Tablets = new javax.swing.JLabel();
        jxtReferenceNo7 = new javax.swing.JTextField();
        jxtLOT = new javax.swing.JTextField();
        jxtIssuedDate = new javax.swing.JTextField();
        L_O_T = new javax.swing.JLabel();
        jxtReferenceNo10 = new javax.swing.JTextField();
        Issued_Date = new javax.swing.JLabel();
        jxtReferenceNo11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jxtExprDate = new javax.swing.JTextField();
        jxtDailyDose = new javax.swing.JTextField();
        Expr_Date = new javax.swing.JLabel();
        jxtReferenceNo14 = new javax.swing.JTextField();
        Daily_Dose = new javax.swing.JLabel();
        jxtReferenceNo15 = new javax.swing.JTextField();
        Further_info = new javax.swing.JLabel();
        Possible_SIde_Effects = new javax.swing.JLabel();
        jxtPossibleSIdeEffects = new javax.swing.JTextField();
        jxtFurtherInfos = new javax.swing.JTextField();
        Sotrage_Info = new javax.swing.JLabel();
        jxtStorageInfo = new javax.swing.JTextField();
        Administration = new javax.swing.JLabel();
        jxtAdminstation = new javax.swing.JTextField();
        Patient_ID = new javax.swing.JLabel();
        How_to_Use = new javax.swing.JLabel();
        jxtHowToUse = new javax.swing.JTextField();
        jxtPatientID = new javax.swing.JTextField();
        Doctor_NHS_No = new javax.swing.JLabel();
        jxtDcotorNHSNo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jxtDriving = new javax.swing.JTextField();
        jxtReferenceNo30 = new javax.swing.JTextField();
        Driving_Machine = new javax.swing.JLabel();
        jxtReferenceNo31 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jBtnDoctor = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jBtnPayments = new javax.swing.JButton();
        jBtnPatient = new javax.swing.JButton();
        jBtnPharmacyOffice = new javax.swing.JButton();
        jBtnGPAppointment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jcmbNameofTablets = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("Reference No:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 290, -1));

        jxtReferenceNo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 310, 30));

        Name_of_Tablet.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Name_of_Tablet.setText("Name of Tablets:");
        getContentPane().add(Name_of_Tablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, -1));

        jxtDose.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 310, 30));

        jxtNumberofTablets.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtNumberofTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 310, 30));

        Dose_mg.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Dose_mg.setText("Dose(mg):");
        getContentPane().add(Dose_mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 250, -1));

        jxtReferenceNo6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 310, 30));

        Number_of_Tablets.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Number_of_Tablets.setText("Number of Tablets:");
        getContentPane().add(Number_of_Tablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 340, -1));

        jxtReferenceNo7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 310, 30));

        jxtLOT.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtLOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 310, 30));

        jxtIssuedDate.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 310, 30));

        L_O_T.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        L_O_T.setText("LOT:");
        getContentPane().add(L_O_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, -1));

        jxtReferenceNo10.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 310, 30));

        Issued_Date.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Issued_Date.setText("Issued Date:");
        getContentPane().add(Issued_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 270, -1));

        jxtReferenceNo11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 310, 30));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jxtExprDate.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtExprDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 310, 30));

        jxtDailyDose.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 310, 30));

        Expr_Date.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Expr_Date.setText("Expr Date:");
        getContentPane().add(Expr_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 250, -1));

        jxtReferenceNo14.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 310, 30));

        Daily_Dose.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Daily_Dose.setText("Daily Dose:");
        getContentPane().add(Daily_Dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 260, -1));

        jxtReferenceNo15.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 310, 30));

        Further_info.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Further_info.setText("Further Infos:");
        getContentPane().add(Further_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 240, -1));

        Possible_SIde_Effects.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Possible_SIde_Effects.setText("Possible Side Effects:");
        getContentPane().add(Possible_SIde_Effects, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 320, -1));

        jxtPossibleSIdeEffects.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jxtPossibleSIdeEffects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxtPossibleSIdeEffectsActionPerformed(evt);
            }
        });
        getContentPane().add(jxtPossibleSIdeEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 340, 30));

        jxtFurtherInfos.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtFurtherInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 340, 30));

        Sotrage_Info.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Sotrage_Info.setText("Storage Info:");
        getContentPane().add(Sotrage_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 240, -1));

        jxtStorageInfo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtStorageInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 340, 30));

        Administration.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Administration.setText("Administation:");
        getContentPane().add(Administration, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 260, -1));

        jxtAdminstation.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtAdminstation, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, 340, 30));

        Patient_ID.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Patient_ID.setText("Patient ID.");
        getContentPane().add(Patient_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 220, -1));

        How_to_Use.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        How_to_Use.setText("How to Use:");
        getContentPane().add(How_to_Use, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 290, -1));

        jxtHowToUse.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtHowToUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 260, 340, 30));

        jxtPatientID.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jxtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxtPatientIDActionPerformed(evt);
            }
        });
        getContentPane().add(jxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 340, 30));

        Doctor_NHS_No.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Doctor_NHS_No.setText("Doctor NHS No.");
        getContentPane().add(Doctor_NHS_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 270, -1));

        jxtDcotorNHSNo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtDcotorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 340, 30));

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jxtDriving.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtDriving, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 340, 30));

        jxtReferenceNo30.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo30, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 340, 30));

        Driving_Machine.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Driving_Machine.setText("Driving/Machine:");
        getContentPane().add(Driving_Machine, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 280, -1));

        jxtReferenceNo31.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo31, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 340, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number Of Tablets", "Reference No.", "Dose(mg)", "Number Of Tablets", "LOT", "Issued Date", "Expr Date", "Daily Dose", "Possible Side Effects", "Further Info", "Storage Info", "Administration", "How To Use", "Patient ID", "Doctor NHS No", "Doctor/Driving"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 1240, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnUpdate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jBtnDoctor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnDoctor.setText("Doctor");
        jBtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDoctorActionPerformed(evt);
            }
        });

        jBtnDelete.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnDelete.setText("Delete");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtnPayments.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnPayments.setText("Payments");
        jBtnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPaymentsActionPerformed(evt);
            }
        });

        jBtnPatient.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnPatient.setText("Patient");
        jBtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPatientActionPerformed(evt);
            }
        });

        jBtnPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnPharmacyOffice.setText("Pharmacy Office");
        jBtnPharmacyOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPharmacyOfficeActionPerformed(evt);
            }
        });

        jBtnGPAppointment.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnGPAppointment.setText("GP Appointment");
        jBtnGPAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGPAppointmentActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setText("Exit");

        jBtnExit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jbtnLogin.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(819, 819, 819)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(149, 149, 149))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnGPAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPharmacyOffice)
                        .addGap(39, 39, 39)
                        .addComponent(jbtnLogin)
                        .addGap(44, 44, 44)
                        .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jBtnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnGPAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPharmacyOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 1240, 60));

        jcmbNameofTablets.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jcmbNameofTablets.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Make Selection", "1.Anti-malarial", "quinine", "quinidine", "chloroquine", "amodiaquine", "mefloquine", "halofantrine", "lumefantrine", "piperaquine", "tafenoquine", "2. Anti-Biotic ", "amoxicillin.", "doxycycline.", "cephalexin.", "ciprofloxacin.", "clindamycin.", "metronidazole.", "azithromycin.", "sulfamethoxazole and trimethopri", "3. Anti-Septic", "Peridex", "Betadine", "Periogard" }));
        jcmbNameofTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameofTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNameofTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 310, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHARMACY SECTION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 10, 390, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 740, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jxtPossibleSIdeEffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxtPossibleSIdeEffectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxtPossibleSIdeEffectsActionPerformed

    private void jxtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxtPatientIDActionPerformed

    private void jcmbNameofTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameofTabletsActionPerformed
        // Tablets provided code:
        if (jcmbNameofTablets.getSelectedItem().equals("quinine")) {
            jxtReferenceNo.setText("AB001");
            jxtDose.setText("30 Days");
            jxtNumberofTablets.setText("32");
            jxtLOT.setText("5767473474");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2022");
            jxtDailyDose.setText("3 Times per Day");
            jxtPossibleSIdeEffects.setText("Fever, Vomiting");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 10 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000001");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");

        }

        if (jcmbNameofTablets.getSelectedItem().equals("chloroquine")) {
            jxtReferenceNo.setText("AB003");
            jxtDose.setText("25 Days");
            jxtNumberofTablets.setText("16");
            jxtLOT.setText("576667");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/07/2022");
            jxtDailyDose.setText("3 Times per Day");
            jxtPossibleSIdeEffects.setText(" Joint paining");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 15 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, ");
            jxtPatientID.setText("0000003");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");
        }

        if (jcmbNameofTablets.getSelectedItem().equals("quinidine")) {
            jxtReferenceNo.setText("AB002");
            jxtDose.setText("20 Days");
            jxtNumberofTablets.setText("16");
            jxtLOT.setText("57667");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2021");
            jxtDailyDose.setText("2 Times per Day");
            jxtPossibleSIdeEffects.setText("Vomiting, Joint paining");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 15 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000002");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("amodiaquine")) {
            jxtReferenceNo.setText("AB003");
            jxtDose.setText("20 Days");
            jxtNumberofTablets.setText("16");
            jxtLOT.setText("57667");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2021");
            jxtDailyDose.setText("2 Times per Day");
            jxtPossibleSIdeEffects.setText("Vomiting, Joint paining");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 15 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000002");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("mefloquine")) {
            jxtReferenceNo.setText("AB005");
            jxtDose.setText("20 Days");
            jxtNumberofTablets.setText("16");
            jxtLOT.setText("57667");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2021");
            jxtDailyDose.setText("2 Times per Day");
            jxtPossibleSIdeEffects.setText("Vomiting, Joint paining");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 15 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000002");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("2. Anti-Biotic ")) {
            jxtReferenceNo.setText("");
            jxtDose.setText("");
            jxtNumberofTablets.setText("");
            jxtLOT.setText("");
            jxtIssuedDate.setText("");
            jxtExprDate.setText("");
            jxtDailyDose.setText("");
            jxtPossibleSIdeEffects.setText("");
            jxtFurtherInfos.setText("");
            jxtStorageInfo.setText("");
            jxtAdminstation.setText("");
            jxtHowToUse.setText("");
            jxtPatientID.setText("");
            jxtDcotorNHSNo.setText("");
            jxtDriving.setText("");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("2. Anti-Septic")) {
            jxtReferenceNo.setText("");
            jxtDose.setText("");
            jxtNumberofTablets.setText("");
            jxtLOT.setText("");
            jxtIssuedDate.setText("");
            jxtExprDate.setText("");
            jxtDailyDose.setText("");
            jxtPossibleSIdeEffects.setText("");
            jxtFurtherInfos.setText("");
            jxtStorageInfo.setText("");
            jxtAdminstation.setText("");
            jxtHowToUse.setText("");
            jxtPatientID.setText("");
            jxtDcotorNHSNo.setText("");
            jxtDriving.setText("");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("2. Anti-Malarial")) {
            jxtReferenceNo.setText("");
            jxtDose.setText("");
            jxtNumberofTablets.setText("");
            jxtLOT.setText("");
            jxtIssuedDate.setText("");
            jxtExprDate.setText("");
            jxtDailyDose.setText("");
            jxtPossibleSIdeEffects.setText("");
            jxtFurtherInfos.setText("");
            jxtStorageInfo.setText("");
            jxtAdminstation.setText("");
            jxtHowToUse.setText("");
            jxtPatientID.setText("");
            jxtDcotorNHSNo.setText("");
            jxtDriving.setText("");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("Make Selection")) {
            jxtReferenceNo.setText("");
            jxtDose.setText("");
            jxtNumberofTablets.setText("");
            jxtLOT.setText("");
            jxtIssuedDate.setText("");
            jxtExprDate.setText("");
            jxtDailyDose.setText("");
            jxtPossibleSIdeEffects.setText("");
            jxtFurtherInfos.setText("");
            jxtStorageInfo.setText("");
            jxtAdminstation.setText("");
            jxtHowToUse.setText("");
            jxtPatientID.setText("");
            jxtDcotorNHSNo.setText("");
            jxtDriving.setText("");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("amoxicillin.")) {
            jxtReferenceNo.setText("AB005");
            jxtDose.setText("20 Days");
            jxtNumberofTablets.setText("16");
            jxtLOT.setText("57667");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2021");
            jxtDailyDose.setText("2 Times per Day");
            jxtPossibleSIdeEffects.setText("Vomiting, Joint paining");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 15 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000002");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("doxycycline.")) {
            jxtReferenceNo.setText("AB002");
            jxtDose.setText("20 Days");
            jxtNumberofTablets.setText("16");
            jxtLOT.setText("57667");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2021");
            jxtDailyDose.setText("2 Times per Day");
            jxtPossibleSIdeEffects.setText("Vomiting, Joint paining");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 15 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000002");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("cephalexin.")) {
            jxtReferenceNo.setText("AB001");
            jxtDose.setText("30 Days");
            jxtNumberofTablets.setText("32");
            jxtLOT.setText("5767473474");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2022");
            jxtDailyDose.setText("3 Times per Day");
            jxtPossibleSIdeEffects.setText("Fever, Vomiting");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 10 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000001");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");

        }
        if (jcmbNameofTablets.getSelectedItem().equals("Peridex")) {
            jxtReferenceNo.setText("AB001");
            jxtDose.setText("30 Days");
            jxtNumberofTablets.setText("32");
            jxtLOT.setText("5767473474");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2022");
            jxtDailyDose.setText("3 Times per Day");
            jxtPossibleSIdeEffects.setText("Fever, Vomiting");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 10 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000001");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("Betadine")) {
            jxtReferenceNo.setText("AB002");
            jxtDose.setText("20 Days");
            jxtNumberofTablets.setText("16");
            jxtLOT.setText("57667");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2021");
            jxtDailyDose.setText("2 Times per Day");
            jxtPossibleSIdeEffects.setText("Vomiting, Joint paining");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 15 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000002");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");
        }
        if (jcmbNameofTablets.getSelectedItem().equals("Periogard")) {
            jxtReferenceNo.setText("AB005");
            jxtDose.setText("20 Days");
            jxtNumberofTablets.setText("16");
            jxtLOT.setText("57667");
            jxtIssuedDate.setText("15/06/2020");
            jxtExprDate.setText("15/06/2021");
            jxtDailyDose.setText("2 Times per Day");
            jxtPossibleSIdeEffects.setText("Vomiting, Joint paining");
            jxtFurtherInfos.setText("If Persist seek assistance");
            jxtStorageInfo.setText("Above 15 Degree Celsius");
            jxtAdminstation.setText("Yes Actioned");
            jxtHowToUse.setText("Use Water, No Alcohol");
            jxtPatientID.setText("0000002");
            jxtDcotorNHSNo.setText("019e7723");
            jxtDriving.setText("No");
        }

    }//GEN-LAST:event_jcmbNameofTabletsActionPerformed

    private void jBtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPatientActionPerformed
        // TODO add your handling code here:
        jBtnPatient.setEnabled(false);
    }//GEN-LAST:event_jBtnPatientActionPerformed

    private void jBtnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPaymentsActionPerformed
        // TODO add your handling code here:
        Payments iPayments = new Payments();
        iPayments.setVisible(true);
    }//GEN-LAST:event_jBtnPaymentsActionPerformed

    private void jBtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDoctorActionPerformed
        // caaling the doctor:
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jBtnDoctorActionPerformed

    private void jBtnGPAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGPAppointmentActionPerformed
        // TODO add your handling code here:
        jBtnGPAppointment.setEnabled(false);
    }//GEN-LAST:event_jBtnGPAppointmentActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // Update Button Actions:
        DefaultTableModel Model = (DefaultTableModel) jTable1.getModel();
        Model.addRow(new Object[]{jcmbNameofTablets.getSelectedItem().toString(),
            jxtReferenceNo.getText(), jxtDose.getText(), jxtNumberofTablets.getText(),
            jxtLOT.getText(), jxtIssuedDate.getText(), jxtExprDate.getText(),
            jxtDailyDose.getText(), jxtPossibleSIdeEffects.getText(), jxtFurtherInfos.getText(),
            jxtStorageInfo.getText(), jxtAdminstation.getText(), jxtHowToUse.getText(),
            jxtPatientID.getText(), jxtDcotorNHSNo.getText(), jxtDriving.getText(),});

    }//GEN-LAST:event_jbtnUpdateActionPerformed
    private JFrame frame;
    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        // Exit Button Code:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are sure you want to exit? ", "Pharmacy Management Systems", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No Data to Delete ", "Pharmacy Management System", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Select a row to delete", "Pharmacy Management System", JOptionPane.OK_OPTION);
            }
        } else {
            Model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // Login Button actions:
        Login ilogin = new Login();
        ilogin.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jBtnPharmacyOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPharmacyOfficeActionPerformed
        // TODO add your handling code here:
        jBtnPharmacyOffice.setEnabled(true);
    }//GEN-LAST:event_jBtnPharmacyOfficeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pharmacy().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administration;
    private javax.swing.JLabel Daily_Dose;
    private javax.swing.JLabel Doctor_NHS_No;
    private javax.swing.JLabel Dose_mg;
    private javax.swing.JLabel Driving_Machine;
    private javax.swing.JLabel Expr_Date;
    private javax.swing.JLabel Further_info;
    private javax.swing.JLabel How_to_Use;
    private javax.swing.JLabel Issued_Date;
    private javax.swing.JLabel L_O_T;
    private javax.swing.JLabel Name_of_Tablet;
    private javax.swing.JLabel Number_of_Tablets;
    private javax.swing.JLabel Patient_ID;
    private javax.swing.JLabel Possible_SIde_Effects;
    private javax.swing.JLabel Sotrage_Info;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnDoctor;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnGPAppointment;
    private javax.swing.JButton jBtnPatient;
    private javax.swing.JButton jBtnPayments;
    private javax.swing.JButton jBtnPharmacyOffice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox jcmbNameofTablets;
    private javax.swing.JTextField jxtAdminstation;
    private javax.swing.JTextField jxtDailyDose;
    private javax.swing.JTextField jxtDcotorNHSNo;
    private javax.swing.JTextField jxtDose;
    private javax.swing.JTextField jxtDriving;
    private javax.swing.JTextField jxtExprDate;
    private javax.swing.JTextField jxtFurtherInfos;
    private javax.swing.JTextField jxtHowToUse;
    private javax.swing.JTextField jxtIssuedDate;
    private javax.swing.JTextField jxtLOT;
    private javax.swing.JTextField jxtNumberofTablets;
    private javax.swing.JTextField jxtPatientID;
    private javax.swing.JTextField jxtPossibleSIdeEffects;
    private javax.swing.JTextField jxtReferenceNo;
    private javax.swing.JTextField jxtReferenceNo10;
    private javax.swing.JTextField jxtReferenceNo11;
    private javax.swing.JTextField jxtReferenceNo14;
    private javax.swing.JTextField jxtReferenceNo15;
    private javax.swing.JTextField jxtReferenceNo30;
    private javax.swing.JTextField jxtReferenceNo31;
    private javax.swing.JTextField jxtReferenceNo6;
    private javax.swing.JTextField jxtReferenceNo7;
    private javax.swing.JTextField jxtStorageInfo;
    // End of variables declaration//GEN-END:variables
}
