/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy.Login;

import Doctor.Doctor;
import Payments.Payments;
import Pharmacy.Pharmacy;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Zubery Msemo, Nobert Okoye , Ahmed Meshref
 */
public class Login extends javax.swing.JFrame {
    int attempt = 0;
    
    
 
        
        
    
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        ImageIcon img;
        img = new ImageIcon("C:\\Users\\Zoubar\\Documents\\NetBeansProjects\\Pharmacy_Project\\src\\Icons/icon1.png");
        this.setIconImage(img.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        jxtUserName = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jCancel = new javax.swing.JButton();
        JExit = new javax.swing.JButton();
        jLogin2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnPharmacy = new javax.swing.JButton();
        jBtnDoctor = new javax.swing.JButton();
        jBtnPayments = new javax.swing.JButton();
        jBtnPatient = new javax.swing.JButton();
        jBtnPharmacyOffice = new javax.swing.JButton();
        jBtnGPAppointments = new javax.swing.JButton();
        jBtnHospital = new javax.swing.JButton();
        jBtnSurgery = new javax.swing.JButton();
        jBtnConsultant = new javax.swing.JButton();
        jBtnSpecialist = new javax.swing.JButton();
        jBtnHelp = new javax.swing.JButton();
        jBtnPharmacist = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Username.setText("Password:");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 120, 40));

        Username1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Username1.setText("UserName:");
        jPanel1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 40));

        jxtUserName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanel1.add(jxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 200, 30));

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, 30));

        jCancel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jCancel.setText("CANCEL");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 120, 40));

        JExit.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        JExit.setText("EXIT");
        JExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JExitActionPerformed(evt);
            }
        });
        jPanel1.add(JExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 100, 40));

        jLogin2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLogin2.setText("LOGIN");
        jLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogin2ActionPerformed(evt);
            }
        });
        jPanel1.add(jLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 40));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setText("Login Screen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 250, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(350, 220, 550, 440);

        jBtnPharmacy.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnPharmacy.setText("Pharmacy");
        jBtnPharmacy.setToolTipText("");
        jBtnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPharmacyActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPharmacy);
        jBtnPharmacy.setBounds(40, 300, 290, 60);

        jBtnDoctor.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnDoctor.setText("Doctor");
        jBtnDoctor.setToolTipText("");
        jBtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDoctor);
        jBtnDoctor.setBounds(40, 220, 290, 60);

        jBtnPayments.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnPayments.setText("Payments");
        jBtnPayments.setToolTipText("");
        jBtnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPaymentsActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPayments);
        jBtnPayments.setBounds(40, 450, 290, 60);

        jBtnPatient.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnPatient.setText("Patient");
        jBtnPatient.setToolTipText("");
        getContentPane().add(jBtnPatient);
        jBtnPatient.setBounds(40, 370, 290, 60);

        jBtnPharmacyOffice.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnPharmacyOffice.setText("Pharmacy Office");
        jBtnPharmacyOffice.setToolTipText("");
        getContentPane().add(jBtnPharmacyOffice);
        jBtnPharmacyOffice.setBounds(40, 600, 290, 60);

        jBtnGPAppointments.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnGPAppointments.setText("GPAppointments");
        jBtnGPAppointments.setToolTipText("");
        getContentPane().add(jBtnGPAppointments);
        jBtnGPAppointments.setBounds(40, 520, 290, 60);

        jBtnHospital.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnHospital.setText("Hospital");
        jBtnHospital.setToolTipText("");
        getContentPane().add(jBtnHospital);
        jBtnHospital.setBounds(930, 300, 280, 60);

        jBtnSurgery.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnSurgery.setText("Surgery");
        jBtnSurgery.setToolTipText("");
        getContentPane().add(jBtnSurgery);
        jBtnSurgery.setBounds(930, 220, 280, 60);

        jBtnConsultant.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnConsultant.setText("Consultant");
        jBtnConsultant.setToolTipText("");
        getContentPane().add(jBtnConsultant);
        jBtnConsultant.setBounds(930, 450, 280, 60);

        jBtnSpecialist.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnSpecialist.setText("Specialist");
        jBtnSpecialist.setToolTipText("");
        getContentPane().add(jBtnSpecialist);
        jBtnSpecialist.setBounds(930, 370, 280, 60);

        jBtnHelp.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnHelp.setText("Help");
        jBtnHelp.setToolTipText("");
        getContentPane().add(jBtnHelp);
        jBtnHelp.setBounds(930, 600, 280, 60);

        jBtnPharmacist.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jBtnPharmacist.setText("Pharmacist");
        jBtnPharmacist.setToolTipText("");
        getContentPane().add(jBtnPharmacist);
        jBtnPharmacist.setBounds(930, 520, 280, 60);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setText("Pharmacy Management Systems");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 0, 1170, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // cancel button code:
        jxtUserName.setText("");
        jPassword.setText("");
        
    }//GEN-LAST:event_jCancelActionPerformed
private JFrame frame;
    private void JExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JExitActionPerformed
        //  exit button instruction here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are sure you want to exit? ", "Pharmacy Management Systems", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_JExitActionPerformed

    private void jLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogin2ActionPerformed
        // Login Code here:
        String UserName = jxtUserName.getText();
        String Password = jPassword.getText();
        
      
           

        

        if (UserName.contains("one")&& (Password.contains("one"))){
            jPassword.setText("");
            jBtnDoctor.setEnabled(true);
            jBtnPharmacy.setEnabled(true);
            jBtnPatient.setEnabled(true);
            jBtnPharmacist.setEnabled(true);
            jBtnSpecialist.setEnabled(true);
            
            jBtnPayments.setEnabled(true);
            jBtnGPAppointments.setEnabled(true);
            jBtnPharmacyOffice.setEnabled(true);
            jBtnSurgery.setEnabled(true);
            jBtnHospital.setEnabled(true);
            jBtnConsultant.setEnabled(true);
            jBtnHelp.setEnabled(true); 
            
        }
        else if (!(UserName.contains("one")&& (Password.contains("one")))){
            
            jxtUserName.setText("");
            jPassword.setText("");
            jBtnDoctor.setEnabled(false);
            jBtnPharmacy.setEnabled(false);
            jBtnPatient.setEnabled(false);
            jBtnPharmacist.setEnabled(false);
            jBtnSpecialist.setEnabled(false);
            jBtnPayments.setEnabled(false);
            jBtnGPAppointments.setEnabled(false);
            jBtnPharmacyOffice.setEnabled(false);
            jBtnSurgery.setEnabled(false);
            jBtnHospital.setEnabled(false);
            jBtnConsultant.setEnabled(false);
            jBtnHelp.setEnabled(false);
            JOptionPane.showMessageDialog(null,"Incorrect Login, Try Again");
            attempt += 1;
            
            
            if (attempt == 3) {
                System.exit(0);
                
            }
            
        }
        
    }//GEN-LAST:event_jLogin2ActionPerformed

    private void jBtnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPharmacyActionPerformed
        // Opening a the pharmacy form:
        Pharmacy MyPharmacy = new Pharmacy();
        MyPharmacy.setVisible(true);
    }//GEN-LAST:event_jBtnPharmacyActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jBtnDoctor.setEnabled(false);
        jBtnPharmacy.setEnabled(false);
        jBtnPatient.setEnabled(false);
        jBtnPharmacist.setEnabled(false);
        jBtnSpecialist.setEnabled(false);
        jBtnPayments.setEnabled(false);
        jBtnGPAppointments.setEnabled(false);
        jBtnPharmacyOffice.setEnabled(false);
        jBtnSurgery.setEnabled(false);
        jBtnHospital.setEnabled(false);
        jBtnConsultant.setEnabled(false);
        jBtnHelp.setEnabled(false);
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jBtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDoctorActionPerformed
        // calling the Doctor app:
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
        
    }//GEN-LAST:event_jBtnDoctorActionPerformed

    private void jBtnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPaymentsActionPerformed
        // TODO add your handling code here:
         Payments iPayments = new Payments();
        iPayments.setVisible(true);
    }//GEN-LAST:event_jBtnPaymentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JExit;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnConsultant;
    private javax.swing.JButton jBtnDoctor;
    private javax.swing.JButton jBtnGPAppointments;
    private javax.swing.JButton jBtnHelp;
    private javax.swing.JButton jBtnHospital;
    private javax.swing.JButton jBtnPatient;
    private javax.swing.JButton jBtnPayments;
    private javax.swing.JButton jBtnPharmacist;
    private javax.swing.JButton jBtnPharmacy;
    private javax.swing.JButton jBtnPharmacyOffice;
    private javax.swing.JButton jBtnSpecialist;
    private javax.swing.JButton jBtnSurgery;
    private javax.swing.JButton jCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLogin2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jxtUserName;
    // End of variables declaration//GEN-END:variables
}
