/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payments;

import Pharmacy.Login.Login;
import Pharmacy.Pharmacy;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zubery Msemo, Ahmed Meshref, Nobert Okoye
 */
public class Payments extends javax.swing.JFrame {

    /**
     * Creates new form Payments
     */
    public Payments() {
        initComponents();
        ImageIcon img;
        img = new ImageIcon("C:\\Users\\Zoubar\\Documents\\NetBeansProjects\\Pharmacy_Project\\src\\Icons/icon1.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDoctorNHSNo = new javax.swing.JLabel();
        jxtDoctorNHSNo = new javax.swing.JTextField();
        Name_of_Tablet = new javax.swing.JLabel();
        jxtFirstName = new javax.swing.JTextField();
        jxtLastName = new javax.swing.JTextField();
        jFirstName = new javax.swing.JLabel();
        jxtReferenceNo6 = new javax.swing.JTextField();
        jLastName = new javax.swing.JLabel();
        jxtReferenceNo7 = new javax.swing.JTextField();
        jxtMedicalCentreName = new javax.swing.JTextField();
        jxtPatient_IDNo = new javax.swing.JTextField();
        jMedicalCentreName = new javax.swing.JLabel();
        jxtReferenceNo10 = new javax.swing.JTextField();
        jPatient_ID = new javax.swing.JLabel();
        jxtReferenceNo11 = new javax.swing.JTextField();
        jxtCentreAdress = new javax.swing.JTextField();
        jxtPostCode = new javax.swing.JTextField();
        jCentreAdress = new javax.swing.JLabel();
        jxtReferenceNo14 = new javax.swing.JTextField();
        jPostCode = new javax.swing.JLabel();
        jxtReferenceNo15 = new javax.swing.JTextField();
        jMedicalCentreRef = new javax.swing.JLabel();
        jxtCost = new javax.swing.JTextField();
        jDoctorEMISNo = new javax.swing.JLabel();
        jxtGrossAmount = new javax.swing.JTextField();
        jGPappointmentRef = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jBtnPharmacy = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jBtnPayments = new javax.swing.JButton();
        jBtnPatient = new javax.swing.JButton();
        jBtnPharmacyOffice = new javax.swing.JButton();
        jBtnGPAppointment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jDoctorMedName = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDoctorNHSNo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jDoctorNHSNo.setText("Doctor NHS No.");
        getContentPane().add(jDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 290, -1));

        jxtDoctorNHSNo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 310, 30));

        Name_of_Tablet.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Name_of_Tablet.setText("Doc Med Name");
        getContentPane().add(Name_of_Tablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, -1));

        jxtFirstName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 310, 30));

        jxtLastName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 310, 30));

        jFirstName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jFirstName.setText("FirstName:");
        getContentPane().add(jFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 250, -1));

        jxtReferenceNo6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 310, 30));

        jLastName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLastName.setText("Last Name:");
        getContentPane().add(jLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 340, -1));

        jxtReferenceNo7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 310, 30));

        jxtMedicalCentreName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtMedicalCentreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 310, 30));

        jxtPatient_IDNo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtPatient_IDNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 310, 30));

        jMedicalCentreName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jMedicalCentreName.setText("Medical Centre Name:");
        getContentPane().add(jMedicalCentreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, -1));

        jxtReferenceNo10.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 310, 30));

        jPatient_ID.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPatient_ID.setText("Patient_ID");
        getContentPane().add(jPatient_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 270, -1));

        jxtReferenceNo11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 310, 30));

        jxtCentreAdress.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtCentreAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 310, 30));

        jxtPostCode.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 310, 30));

        jCentreAdress.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jCentreAdress.setText("Centre Address:");
        getContentPane().add(jCentreAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 250, -1));

        jxtReferenceNo14.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 310, 30));

        jPostCode.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPostCode.setText("Post Code:");
        getContentPane().add(jPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 260, -1));

        jxtReferenceNo15.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtReferenceNo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 310, 30));

        jMedicalCentreRef.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jMedicalCentreRef.setText("Cost:");
        getContentPane().add(jMedicalCentreRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 160, 60));

        jxtCost.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jxtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxtCostActionPerformed(evt);
            }
        });
        getContentPane().add(jxtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 340, 30));

        jDoctorEMISNo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jDoctorEMISNo.setText("Gross Amount:");
        getContentPane().add(jDoctorEMISNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 270, -1));

        jxtGrossAmount.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jxtGrossAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 340, 30));

        jGPappointmentRef.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(jGPappointmentRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 280, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doc Med Name", "Doctor NHS No", "First Name", "Second Name", "Medical Centre Name", "Patient_ID", "Centre Adress", "Post Code", "Cost", "Gross Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 1240, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnUpdate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jBtnPharmacy.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnPharmacy.setText("Pharmacy");
        jBtnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPharmacyActionPerformed(evt);
            }
        });

        jBtnDelete.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnDelete.setText("Delete");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtnPayments.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnPayments.setText("Payments");
        jBtnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPaymentsActionPerformed(evt);
            }
        });

        jBtnPatient.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnPatient.setText("Patient");
        jBtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPatientActionPerformed(evt);
            }
        });

        jBtnPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnPharmacyOffice.setText("Pharmacy Office");
        jBtnPharmacyOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPharmacyOfficeActionPerformed(evt);
            }
        });

        jBtnGPAppointment.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnGPAppointment.setText("GP Appointment");
        jBtnGPAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGPAppointmentActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setText("Exit");

        jBtnExit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jbtnLogin.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(819, 819, 819)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(149, 149, 149))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnGPAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPharmacyOffice)
                        .addGap(39, 39, 39)
                        .addComponent(jbtnLogin)
                        .addGap(44, 44, 44)
                        .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jBtnPharmacy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnGPAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPharmacyOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 1240, 60));

        jDoctorMedName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Make Selection", "1.Anti-malarial", "quinine", "quinidine", "chloroquine", "amodiaquine", "mefloquine", "halofantrine", "lumefantrine", "piperaquine", "tafenoquine", "2. Anti-Biotic ", "amoxicillin.", "doxycycline.", "cephalexin.", "ciprofloxacin.", "clindamycin.", "metronidazole.", "azithromycin.", "sulfamethoxazole and trimethopri", "3. Anti-Septic", "Peridex", "Betadine", "Periogard" }));
        jDoctorMedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoctorMedNameActionPerformed(evt);
            }
        });
        getContentPane().add(jDoctorMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 310, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAYMENTS SECTION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 10, 390, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 740, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jxtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxtCostActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // Update Button Actions:
        DefaultTableModel Model = (DefaultTableModel) jTable1.getModel();
        Model.addRow(new Object[]{jDoctorMedName.getSelectedItem().toString(),
            jxtDoctorNHSNo.getText(),jxtFirstName.getText(),jxtLastName.getText(),
            jxtMedicalCentreName.getText(),jxtPatient_IDNo.getText(), jxtCentreAdress.getText(),
            jxtPostCode.getText(), jxtCost.getText(),
             jxtGrossAmount.getText(),});
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jBtnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPharmacyActionPerformed
        // TODO add your handling code here:
        Pharmacy iPharmacy = new Pharmacy();
        iPharmacy.setVisible(true);
    }//GEN-LAST:event_jBtnPharmacyActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount()== 0){
                JOptionPane.showMessageDialog(null,  "No Data to Delete ", "Pharmacy Management System" , JOptionPane.OK_OPTION);
            }else {
                JOptionPane.showMessageDialog(null,"Select a row to delete", "Pharmacy Management System", JOptionPane.OK_OPTION);
            }
        }else {
            Model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPaymentsActionPerformed
        // TODO add your handling code here:
        jBtnPayments.setEnabled(false);
    }//GEN-LAST:event_jBtnPaymentsActionPerformed

    private void jBtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPatientActionPerformed
        // TODO add your handling code here:
        jBtnPatient.setEnabled(false);
    }//GEN-LAST:event_jBtnPatientActionPerformed

    private void jBtnGPAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGPAppointmentActionPerformed
        // TODO add your handling code here:
        jBtnGPAppointment.setEnabled(false);
    }//GEN-LAST:event_jBtnGPAppointmentActionPerformed
private JFrame frame;
    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        // Exit Button Code:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are sure you want to exit? ", "Pharmacy Management Systems", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // Login Button actions:
        Login ilogin = new Login();
        ilogin.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jDoctorMedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoctorMedNameActionPerformed
        // TODO add your handling code here:
        if (jDoctorMedName.getSelectedItem().equals("quinine")) {

            jxtDoctorNHSNo.setText("DR001");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 5.00");
            jxtGrossAmount.setText("$ 5.30");
           
        
        }
         if (jDoctorMedName.getSelectedItem().equals("quinidine")) {

            jxtDoctorNHSNo.setText("DR001");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 10.00");
            jxtGrossAmount.setText("$ 10.30");
        }
          if (jDoctorMedName.getSelectedItem().equals("chloroquine")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 4.00");
            jxtGrossAmount.setText("$ 4.50");
        }
           if (jDoctorMedName.getSelectedItem().equals("amodiaquine")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 3.00");
            jxtGrossAmount.setText("$ 5.00");
        }
            if (jDoctorMedName.getSelectedItem().equals("amoxicillin.")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 4.50");
            jxtGrossAmount.setText("$ 5.00");
        }
        if (jDoctorMedName.getSelectedItem().equals("doxycycline.")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 8.00");
            jxtGrossAmount.setText("$ 8.90");
        }
        if (jDoctorMedName.getSelectedItem().equals("cephalexin.")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 12.00");
            jxtGrossAmount.setText("$ 12.50");
        }
        if (jDoctorMedName.getSelectedItem().equals("Peridex")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 7.00");
            jxtGrossAmount.setText("$ 7.00");
        }
        if (jDoctorMedName.getSelectedItem().equals("Betadine")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 11.00");
            jxtGrossAmount.setText("$ 11.90");
        }
        if (jDoctorMedName.getSelectedItem().equals("Periogard")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("AfyaNjema Hospital");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("Po box 11875,Kigali");
            jxtPostCode.setText("11875");
            jxtCost.setText("$ 14.50");
            jxtGrossAmount.setText("$ 15.00");
        }
        if (jDoctorMedName.getSelectedItem().equals("3. Anti-Septic")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("");
            jxtPostCode.setText("");
            jxtCost.setText("$ 0.00");
            jxtGrossAmount.setText("$ 00.00");
        }
        if (jDoctorMedName.getSelectedItem().equals("3. Anti-Biotic")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("");
            jxtPostCode.setText("");
            jxtCost.setText("$ 0.00");
            jxtGrossAmount.setText("$ 00.00");
        }
        if (jDoctorMedName.getSelectedItem().equals("3. Anti-Malarial")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("");
            jxtPostCode.setText("");
            jxtCost.setText("$ 0.00");
            jxtGrossAmount.setText("$ 00.00");
        }
        if (jDoctorMedName.getSelectedItem().equals("Make Selection")) {

            jxtDoctorNHSNo.setText("");
            jxtFirstName.setText("");
            jxtLastName.setText("");
            jxtMedicalCentreName.setText("");
            jxtPatient_IDNo.setText("");
            jxtCentreAdress.setText("");
            jxtPostCode.setText("");
            jxtCost.setText("$ 0.00");
            jxtGrossAmount.setText("$ 00.00");
        }
        
           
           
    }//GEN-LAST:event_jDoctorMedNameActionPerformed

    private void jBtnPharmacyOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPharmacyOfficeActionPerformed
        // TODO add your handling code here:
        jBtnPharmacyOffice.setEnabled(false);
    }//GEN-LAST:event_jBtnPharmacyOfficeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Payments().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name_of_Tablet;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnGPAppointment;
    private javax.swing.JButton jBtnPatient;
    private javax.swing.JButton jBtnPayments;
    private javax.swing.JButton jBtnPharmacy;
    private javax.swing.JButton jBtnPharmacyOffice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCentreAdress;
    private javax.swing.JLabel jDoctorEMISNo;
    private javax.swing.JComboBox jDoctorMedName;
    private javax.swing.JLabel jDoctorNHSNo;
    private javax.swing.JLabel jFirstName;
    private javax.swing.JLabel jGPappointmentRef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLastName;
    private javax.swing.JLabel jMedicalCentreName;
    private javax.swing.JLabel jMedicalCentreRef;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPatient_ID;
    private javax.swing.JLabel jPostCode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jxtCentreAdress;
    private javax.swing.JTextField jxtCost;
    private javax.swing.JTextField jxtDoctorNHSNo;
    private javax.swing.JTextField jxtFirstName;
    private javax.swing.JTextField jxtGrossAmount;
    private javax.swing.JTextField jxtLastName;
    private javax.swing.JTextField jxtMedicalCentreName;
    private javax.swing.JTextField jxtPatient_IDNo;
    private javax.swing.JTextField jxtPostCode;
    private javax.swing.JTextField jxtReferenceNo10;
    private javax.swing.JTextField jxtReferenceNo11;
    private javax.swing.JTextField jxtReferenceNo14;
    private javax.swing.JTextField jxtReferenceNo15;
    private javax.swing.JTextField jxtReferenceNo6;
    private javax.swing.JTextField jxtReferenceNo7;
    // End of variables declaration//GEN-END:variables
}
